create table if not exists public.test (
    id bigint generated by default as identity primary key,
    dog text not null,
    value integer not null
);

alter table public.test enable row level security;

create policy "Allow all on test" on public.test
    for all using (true) with check (true);

create or replace function public.test_void_func() returns void as $$
begin
    null;
end;
$$ language plpgsql;

create or replace function public.test_echo(val text) returns text as $$
begin
    return val;
end;
$$ language plpgsql;

create or replace function public.test_get_test_rows() returns setof public.test as $$
begin
    return query select * from public.test;
end;
$$ language plpgsql;

create or replace function public.test_add_numbers(a integer, b integer) returns integer as $$
begin
    return a + b;
end;
$$ language plpgsql;

create or replace function public.test_json_echo(data jsonb) returns jsonb as $$
begin
    return data;
end;
$$ language plpgsql;

create or replace function public.test_greet(name text default 'World') returns text as $$
begin
    return 'Hello, ' || name || '!';
end;
$$ language plpgsql;
